"""Private forecast storage for the Event Probability workspace.

Every forecast query is scoped by both the authenticated user and workspace.
Rows created before Phase 2 have a NULL owner and are deliberately not exposed
to signed-in users; this prevents legacy shared history from leaking between
accounts.
"""

import json
import os
import sqlite3
from collections.abc import Mapping
from datetime import datetime, timezone

from config import DB_PATH, STORAGE_DIR


def _is_postgres():
    return os.getenv("DATABASE_URL", "").strip().lower().startswith(("postgresql://", "postgres://"))


def _conn():
    if _is_postgres():
        import psycopg
        return psycopg.connect(os.environ["DATABASE_URL"], autocommit=False)
    STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DB_PATH, timeout=30)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA busy_timeout=30000")
    connection.execute("PRAGMA foreign_keys=ON")
    return connection


def _ensure_sqlite_column(connection, table, column, definition):
    columns = {row[1] for row in connection.execute(f"PRAGMA table_info({table})")}
    if column not in columns:
        connection.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def _scope(owner_user_id, workspace_id):
    try:
        owner = int(owner_user_id)
    except (TypeError, ValueError) as exc:
        raise ValueError("A valid forecast owner is required.") from exc
    if owner < 1:
        raise ValueError("A valid forecast owner is required.")
    workspace = str(workspace_id or "default").strip()[:64] or "default"
    return owner, workspace


def init_db():
    if _is_postgres():
        with _conn() as connection:
            connection.execute("""CREATE TABLE IF NOT EXISTS forecasts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL, query TEXT NOT NULL, horizon TEXT, category TEXT,
                result_json TEXT NOT NULL, owner_user_id BIGINT, workspace_id TEXT NOT NULL DEFAULT 'default'
            )""")
            connection.execute("ALTER TABLE forecasts ADD COLUMN IF NOT EXISTS owner_user_id BIGINT")
            connection.execute("ALTER TABLE forecasts ADD COLUMN IF NOT EXISTS workspace_id TEXT NOT NULL DEFAULT 'default'")
            connection.execute("""CREATE TABLE IF NOT EXISTS evidence (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                forecast_id BIGINT, source TEXT, title TEXT, url TEXT, published_at TEXT,
                polarity DOUBLE PRECISION, reliability DOUBLE PRECISION, snippet TEXT, raw_json TEXT,
                FOREIGN KEY(forecast_id) REFERENCES forecasts(id) ON DELETE CASCADE
            )""")
            connection.execute("CREATE INDEX IF NOT EXISTS idx_evidence_forecast ON evidence(forecast_id)")
            connection.execute("CREATE INDEX IF NOT EXISTS idx_forecasts_owner ON forecasts(owner_user_id,workspace_id,id DESC)")
            connection.execute("CREATE TABLE IF NOT EXISTS research_cache (cache_key TEXT PRIMARY KEY, created_at TEXT NOT NULL, payload_json TEXT NOT NULL)")
            connection.execute("""CREATE TABLE IF NOT EXISTS forecast_reviews (
                forecast_id BIGINT PRIMARY KEY, saved BOOLEAN NOT NULL DEFAULT FALSE, note TEXT NOT NULL DEFAULT '',
                resolved_outcome TEXT, resolved_at TEXT, updated_at TEXT NOT NULL,
                FOREIGN KEY(forecast_id) REFERENCES forecasts(id) ON DELETE CASCADE
            )""")
        return

    with _conn() as connection:
        connection.executescript("""
        CREATE TABLE IF NOT EXISTS forecasts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL, query TEXT NOT NULL, horizon TEXT, category TEXT,
            result_json TEXT NOT NULL, owner_user_id INTEGER, workspace_id TEXT NOT NULL DEFAULT 'default'
        );
        CREATE TABLE IF NOT EXISTS evidence (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            forecast_id INTEGER, source TEXT, title TEXT, url TEXT, published_at TEXT,
            polarity REAL, reliability REAL, snippet TEXT, raw_json TEXT,
            FOREIGN KEY(forecast_id) REFERENCES forecasts(id) ON DELETE CASCADE
        );
        CREATE INDEX IF NOT EXISTS idx_evidence_forecast ON evidence(forecast_id);
        CREATE TABLE IF NOT EXISTS research_cache (cache_key TEXT PRIMARY KEY, created_at TEXT NOT NULL, payload_json TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS forecast_reviews (
            forecast_id INTEGER PRIMARY KEY, saved INTEGER NOT NULL DEFAULT 0, note TEXT NOT NULL DEFAULT '',
            resolved_outcome TEXT, resolved_at TEXT, updated_at TEXT NOT NULL,
            FOREIGN KEY(forecast_id) REFERENCES forecasts(id) ON DELETE CASCADE
        );
        """)
        _ensure_sqlite_column(connection, "forecasts", "owner_user_id", "INTEGER")
        _ensure_sqlite_column(connection, "forecasts", "workspace_id", "TEXT NOT NULL DEFAULT 'default'")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_forecasts_owner ON forecasts(owner_user_id,workspace_id,id DESC)")


def readiness_check():
    """Return a non-sensitive storage readiness result."""
    try:
        init_db()
        with _conn() as connection:
            connection.execute("SELECT 1").fetchone()
        return True
    except Exception:
        return False


def save_forecast(query, horizon, category, result, evidence_rows, *, owner_user_id, workspace_id="default"):
    owner, workspace = _scope(owner_user_id, workspace_id)
    now = datetime.now(timezone.utc).isoformat()
    with _conn() as connection:
        if _is_postgres():
            cursor = connection.execute(
                "INSERT INTO forecasts(created_at,query,horizon,category,result_json,owner_user_id,workspace_id) VALUES(%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (now, query, horizon, category, json.dumps(result, ensure_ascii=False), owner, workspace),
            )
            forecast_id = cursor.fetchone()[0]
            marker = "%s"
        else:
            cursor = connection.execute(
                "INSERT INTO forecasts(created_at,query,horizon,category,result_json,owner_user_id,workspace_id) VALUES(?,?,?,?,?,?,?)",
                (now, query, horizon, category, json.dumps(result, ensure_ascii=False), owner, workspace),
            )
            forecast_id = cursor.lastrowid
            marker = "?"
        evidence_sql = (
            "INSERT INTO evidence(forecast_id,source,title,url,published_at,polarity,reliability,snippet,raw_json) "
            f"VALUES({','.join([marker] * 9)})"
        )
        for evidence in evidence_rows:
            connection.execute(evidence_sql, (
                forecast_id, evidence.get("source"), evidence.get("title"), evidence.get("url"),
                evidence.get("published_at"), evidence.get("polarity", 0.0), evidence.get("reliability", 0.5),
                evidence.get("snippet"), json.dumps(evidence, ensure_ascii=False),
            ))
    return forecast_id


def _review_dict(row=None):
    if row is None:
        return {"saved": False, "note": "", "resolved_outcome": None, "resolved_at": None, "updated_at": None}
    if isinstance(row, Mapping) or isinstance(row, sqlite3.Row):
        data = dict(row)
        return {
            "saved": bool(data.get("saved")), "note": data.get("note") or "",
            "resolved_outcome": data.get("resolved_outcome"), "resolved_at": data.get("resolved_at"),
            "updated_at": data.get("updated_at"),
        }
    return {"saved": bool(row[0]), "note": row[1] or "", "resolved_outcome": row[2], "resolved_at": row[3], "updated_at": row[4]}


def _owned_forecast_exists(connection, forecast_id, owner, workspace):
    marker = "%s" if _is_postgres() else "?"
    return connection.execute(
        f"SELECT 1 FROM forecasts WHERE id={marker} AND owner_user_id={marker} AND workspace_id={marker}",
        (forecast_id, owner, workspace),
    ).fetchone() is not None


def get_review(forecast_id, *, owner_user_id, workspace_id="default"):
    owner, workspace = _scope(owner_user_id, workspace_id)
    with _conn() as connection:
        if not _owned_forecast_exists(connection, forecast_id, owner, workspace):
            return None
        marker = "%s" if _is_postgres() else "?"
        row = connection.execute(
            f"SELECT saved,note,resolved_outcome,resolved_at,updated_at FROM forecast_reviews WHERE forecast_id={marker}",
            (forecast_id,),
        ).fetchone()
    return _review_dict(row)


def update_review(forecast_id, updates, *, owner_user_id, workspace_id="default"):
    owner, workspace = _scope(owner_user_id, workspace_id)
    init_db()
    forecast = get_forecast(forecast_id, owner_user_id=owner, workspace_id=workspace)
    if not forecast:
        return None
    review = forecast["review"]
    if "saved" in updates:
        review["saved"] = bool(updates.get("saved"))
    if "note" in updates:
        review["note"] = str(updates.get("note") or "").strip()[:2000]
    if "resolved_outcome" in updates:
        candidate = str(updates.get("resolved_outcome") or "").strip() or None
        allowed = {row.get("candidate") for row in forecast.get("result", {}).get("ranked", [])}
        if candidate and candidate not in allowed:
            raise ValueError("Observed outcome must match one of the forecast scenarios.")
        review["resolved_outcome"] = candidate
        review["resolved_at"] = datetime.now(timezone.utc).isoformat() if candidate else None
    now = datetime.now(timezone.utc).isoformat()
    with _conn() as connection:
        if not _owned_forecast_exists(connection, forecast_id, owner, workspace):
            return None
        if _is_postgres():
            connection.execute("""INSERT INTO forecast_reviews(forecast_id,saved,note,resolved_outcome,resolved_at,updated_at)
                VALUES(%s,%s,%s,%s,%s,%s) ON CONFLICT(forecast_id) DO UPDATE SET
                saved=EXCLUDED.saved,note=EXCLUDED.note,resolved_outcome=EXCLUDED.resolved_outcome,
                resolved_at=EXCLUDED.resolved_at,updated_at=EXCLUDED.updated_at""",
                (forecast_id, review["saved"], review["note"], review["resolved_outcome"], review["resolved_at"], now))
        else:
            connection.execute("""INSERT INTO forecast_reviews(forecast_id,saved,note,resolved_outcome,resolved_at,updated_at)
                VALUES(?,?,?,?,?,?) ON CONFLICT(forecast_id) DO UPDATE SET
                saved=excluded.saved,note=excluded.note,resolved_outcome=excluded.resolved_outcome,
                resolved_at=excluded.resolved_at,updated_at=excluded.updated_at""",
                (forecast_id, int(review["saved"]), review["note"], review["resolved_outcome"], review["resolved_at"], now))
    return {**review, "updated_at": now}


def recent_forecasts(limit=20, saved_only=False, *, owner_user_id, workspace_id="default"):
    owner, workspace = _scope(owner_user_id, workspace_id)
    init_db()
    limit = max(1, min(250, int(limit)))
    with _conn() as connection:
        if _is_postgres():
            saved_clause = " AND COALESCE(r.saved,FALSE)=TRUE" if saved_only else ""
            rows = connection.execute(f"""SELECT f.id,f.created_at,f.query,f.horizon,f.category,f.result_json,
                COALESCE(r.saved,FALSE),COALESCE(r.note,''),r.resolved_outcome,r.resolved_at,r.updated_at
                FROM forecasts f LEFT JOIN forecast_reviews r ON r.forecast_id=f.id
                WHERE f.owner_user_id=%s AND f.workspace_id=%s{saved_clause}
                ORDER BY f.id DESC LIMIT %s""", (owner, workspace, limit)).fetchall()
            return [{"id": row[0], "created_at": row[1], "query": row[2], "horizon": row[3], "category": row[4],
                     "result": json.loads(row[5]), "review": _review_dict(row[6:11])} for row in rows]
        saved_clause = " AND COALESCE(r.saved,0)=1" if saved_only else ""
        rows = connection.execute(f"""SELECT f.id,f.created_at,f.query,f.horizon,f.category,f.result_json,
            COALESCE(r.saved,0) AS saved,COALESCE(r.note,'') AS note,r.resolved_outcome,r.resolved_at,r.updated_at
            FROM forecasts f LEFT JOIN forecast_reviews r ON r.forecast_id=f.id
            WHERE f.owner_user_id=? AND f.workspace_id=?{saved_clause}
            ORDER BY f.id DESC LIMIT ?""", (owner, workspace, limit)).fetchall()
    output = []
    for row in rows:
        item = dict(row)
        review = _review_dict(item)
        for key in ("saved", "note", "resolved_outcome", "resolved_at", "updated_at"):
            item.pop(key, None)
        item["result"] = json.loads(item.pop("result_json"))
        item["review"] = review
        output.append(item)
    return output


def latest_comparable(category, horizon, factor, focus, *, owner_user_id, workspace_id="default"):
    try:
        rows = recent_forecasts(60, owner_user_id=owner_user_id, workspace_id=workspace_id)
        for row in rows:
            result = row.get("result", {})
            if (row.get("category") == category and row.get("horizon") == horizon and result.get("factor") == factor
                    and (result.get("focus") or "") == (focus or "")):
                return row
    except (OSError, sqlite3.DatabaseError, ValueError):
        return None
    return None


def calibration_summary(limit=250, *, owner_user_id, workspace_id="default"):
    rows = recent_forecasts(limit, owner_user_id=owner_user_id, workspace_id=workspace_id)
    resolved = [row for row in rows if row.get("review", {}).get("resolved_outcome")]
    if not resolved:
        return {"resolved_forecasts": 0, "brier_score": None, "top_outcome_accuracy_pct": None, "calibration_buckets": [], "status": "needs_resolutions"}
    brier_values, top_hits, buckets = [], 0, {}
    for row in resolved:
        ranked = row.get("result", {}).get("ranked", [])
        observed = row["review"]["resolved_outcome"]
        probabilities = {item.get("candidate"): float(item.get("normalized_probability", item.get("probability", 0)) or 0) / 100 for item in ranked}
        brier_values.append(sum((probability - (1.0 if candidate == observed else 0.0)) ** 2 for candidate, probability in probabilities.items()))
        top = max(ranked, key=lambda item: float(item.get("normalized_probability", item.get("probability", 0)) or 0), default={})
        top_probability = float(top.get("normalized_probability", top.get("probability", 0)) or 0)
        hit = int(top.get("candidate") == observed)
        top_hits += hit
        lower = int(top_probability // 10) * 10
        key = f"{lower}–{min(100, lower + 9)}%"
        bucket = buckets.setdefault(key, {"label": key, "forecasts": 0, "predicted_pct_total": 0.0, "observed_hits": 0})
        bucket["forecasts"] += 1
        bucket["predicted_pct_total"] += top_probability
        bucket["observed_hits"] += hit
    calibration_buckets = [{
        "label": bucket["label"], "forecasts": bucket["forecasts"],
        "average_predicted_pct": round(bucket["predicted_pct_total"] / bucket["forecasts"], 1),
        "observed_frequency_pct": round(bucket["observed_hits"] / bucket["forecasts"] * 100, 1),
    } for bucket in buckets.values()]
    return {
        "resolved_forecasts": len(resolved), "brier_score": round(sum(brier_values) / len(brier_values), 3),
        "top_outcome_accuracy_pct": round(top_hits / len(resolved) * 100, 1),
        "calibration_buckets": sorted(calibration_buckets, key=lambda row: row["average_predicted_pct"]),
        "status": "calibrating" if len(resolved) < 20 else "measured",
    }


def get_forecast(forecast_id, *, owner_user_id, workspace_id="default"):
    owner, workspace = _scope(owner_user_id, workspace_id)
    init_db()
    with _conn() as connection:
        if _is_postgres():
            row = connection.execute(
                "SELECT id,created_at,query,horizon,category,result_json FROM forecasts WHERE id=%s AND owner_user_id=%s AND workspace_id=%s",
                (forecast_id, owner, workspace),
            ).fetchone()
            if not row:
                return None
            evidence = connection.execute(
                "SELECT source,title,url,published_at,polarity,reliability,snippet FROM evidence WHERE forecast_id=%s ORDER BY reliability DESC, published_at DESC",
                (forecast_id,),
            ).fetchall()
            result = {"id": row[0], "created_at": row[1], "query": row[2], "horizon": row[3], "category": row[4],
                      "result": json.loads(row[5]), "evidence": [
                          {"source": item[0], "title": item[1], "url": item[2], "published_at": item[3],
                           "polarity": item[4], "reliability": item[5], "snippet": item[6]} for item in evidence]}
        else:
            row = connection.execute(
                "SELECT id,created_at,query,horizon,category,result_json FROM forecasts WHERE id=? AND owner_user_id=? AND workspace_id=?",
                (forecast_id, owner, workspace),
            ).fetchone()
            if not row:
                return None
            evidence = connection.execute(
                "SELECT source,title,url,published_at,polarity,reliability,snippet FROM evidence WHERE forecast_id=? ORDER BY reliability DESC, published_at DESC",
                (forecast_id,),
            ).fetchall()
            result = dict(row)
            result["result"] = json.loads(result.pop("result_json"))
            result["evidence"] = [dict(item) for item in evidence]
    result["review"] = get_review(forecast_id, owner_user_id=owner, workspace_id=workspace) or _review_dict()
    return result
